Repository advaithsrao/694Team14Dbms2023, pull requests merged in 2023-04, with the labels that each got.

#1 asr209: Added Requirements.txt and updated README.md
  README.md
  requirements.txt
Labels: documentation, code

#3 Added matplotlib, seaborn and wordcloud and upgraded pandas
  requirements.txt
Labels: documentation, enhancement

#6 Fm466 cicd
  .github/workflows/github_pipeline.yml
Labels: documentation, code

#8 changes to github action file
  .github/workflows/github_pipeline.yml
Labels: bug

#12 Appended corona out 2 zip data to the main data
  notebooks/.ipynb_checkpoints/Task1_Data_Summary-checkpoint.ipynb
  notebooks/Task1_Data_Summary.ipynb
Labels: task 1

#13 added psycopg2 and sqlalchemy to requirements.txt
  requirements.txt
Labels: documentation, task 2

#15 Setup script for relational DB
  README.md
  config.ini
  scripts/setup/relationalDB.sh
Labels: documentation, enhancement, code, task 2

#16 Relational database create and push scripts
  config.ini
  notebooks/vg422/DataLoad.ipynb
  scripts/relationalDB.py
  scripts/setup/relationalDB.sh
Labels: enhancement, code, task 2

#18 Created utils.py; Added connection to sql database inside utils.py
  scripts/relationalDB.py
  scripts/utils.py
Labels: documentation, enhancement, code, task 2

#24 File path to data used in relationalDB.py changed to ./data/file.json
  scripts/relationalDB.py
Labels: bug, code, task 2

#29 added function for global config.ini load to utils.py
  scripts/utils.py
Labels: bug, documentation, help wanted

#30 Setup scripts kibana for elasticsearch
  config.ini
  outputs/nonrelationalDB.out
  outputs/relationalDB.out
  scripts/setup/nonrelationalDB.sh
Labels: documentation, enhancement, code, task 4

#32 changed logic for original_tweet_flag
  scripts/relationalDB.py
Labels: code, task 2

#34 changed flag format for tweet table
  scripts/relationalDB.py
Labels: code, task 2

#35 changes in relational table
  scripts/relationalDB.py
Labels: code, task 2

#36 ElasticSearchIP addition to nonrelational setup script
  scripts/setup/nonrelationalDB.sh
Labels: documentation, enhancement, code, task 2

#37 changes in nonrelationalDB script
  scripts/nonrelationalDB.py
Labels: code, task 2

#38 Vg422 task2 nonrelational
  scripts/nonrelationalDB.py
Labels: code, task 2

#41 reverted issue to before error; fix for quoted_tweet_flag
  scripts/relationalDB.py
Labels: documentation, code, task 2

#42 Added postgres screenshots to outputs dir
  outputs/.DS_Store
  outputs/postgresLayout.png
  outputs/postgresLogs.png
  outputs/postgresQuotedTweets.png
  outputs/postgresReply.png
  outputs/postgresRetweets.png
  outputs/postgresTables.png
  outputs/postgresTweets.png
  outputs/postgresUserProfile.png
Labels: documentation, code, task 2

#44 changes in relationalDB.py
  scripts/relationalDB.py
Labels: code, task 2

#47 fixed logic for flags
  scripts/relationalDB.py
Labels: code, task 2

#48 task3 V2 push with function comments
  .github/workflows/github_pipeline.yml
  scripts/cache.py
  scripts/relationalDB.py
  scripts/utils.py
Labels: documentation, enhancement, code, task 3

#49 error fix task 3
  scripts/cache.py
  scripts/relationalDB.py
  scripts/utils.py
Labels: documentation, enhancement, code, task 3

#51 changes in relational database reply table
  scripts/relationalDB.py
Labels: code, task 2

#52 Added cache stale remover file
  scripts/cache.py
  scripts/staleCacheChecker.py
Labels: documentation, code, task 3

#56 Made search case insensitive
  scripts/search.py
Labels: task 4
